# Generated by Django 5.1.2 on 2024-10-16 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Auteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("biographie", models.TextField()),
                ("date_de_naissance", models.DateField()),
                ("date_de_décès", models.DateField(null=True)),
                ("nationalité", models.CharField(max_length=100)),
                ("photo", models.ImageField(null=True, upload_to="auteurs/")),
            ],
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Editeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("adresse", models.TextField()),
                ("site_web", models.URLField(blank=True, null=True)),
                ("email_contact", models.EmailField(max_length=254)),
                ("description", models.TextField(blank=True, null=True)),
                ("logo", models.ImageField(null=True, upload_to="logo_editeurs/")),
            ],
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                    ),
                ),
                ("commentaire", models.TextField()),
                ("date_evaluation", models.DateTimeField(auto_now_add=True)),
                ("recommande", models.BooleanField()),
                ("titre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Exemplaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "état",
                    models.CharField(
                        choices=[
                            ("Neuf", "Neuf"),
                            ("Bon état", "Bon état"),
                            ("Mauvais état", "Mauvais état"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_acquisition", models.DateField()),
                ("localisation", models.CharField(max_length=255)),
                ("disponibilité", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Emprunt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_emprunt", models.DateTimeField(auto_now_add=True)),
                ("date_retour_prévue", models.DateTimeField()),
                ("date_retour_effective", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("En cours", "En cours"),
                            ("Terminé", "Terminé"),
                            ("En retard", "En retard"),
                        ],
                        max_length=50,
                    ),
                ),
                ("remarques", models.TextField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exemplaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emprunts",
                        to="quickstart.exemplaire",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Livre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("résumé", models.TextField()),
                ("date_de_publication", models.DateField()),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("nombre_de_pages", models.PositiveIntegerField()),
                ("langue", models.CharField(max_length=100)),
                (
                    "image_de_couverture",
                    models.ImageField(null=True, upload_to="couvertures/"),
                ),
                ("éditeur", models.CharField(max_length=255)),
                ("format", models.CharField(max_length=50)),
                (
                    "auteurs",
                    models.ManyToManyField(
                        related_name="livres", to="quickstart.auteur"
                    ),
                ),
                (
                    "catégories",
                    models.ManyToManyField(
                        related_name="livres", to="quickstart.categorie"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exemplaire",
            name="livre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exemplaires",
                to="quickstart.livre",
            ),
        ),
        migrations.CreateModel(
            name="Commentaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                ("date_publication", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                ("modéré", models.BooleanField(default=False)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "livre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires",
                        to="quickstart.livre",
                    ),
                ),
            ],
        ),
    ]
